version: "3"
services:
    python:
        build: .
        container_name: myapp-py
        ports:
            - "8000:8000"
        volumes:
            - "./:/code"
        command: python manage.py runserver 0.0.0.0:8000
        # depends_on:
        #     - db
    # db:
    #     image: postgres:11